import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

// icons
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import code from "../assets/code.png";
import design from "../assets/design.png";
import consulting from "../assets/consulting.png";

import web1 from "../assets/web1.png";
import web2 from "../assets/web2.png";
import web3 from "../assets/web3.png";
import web4 from "../assets/web4.png";
import web5 from "../assets/web5.png";
import web6 from "../assets/web6.png";

// 3d image
import devstan from "../assets/dev-ed-wave.png";

export default function Home() {
  // dark/light mode
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>stanCodes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        {/*Intro page*/}
        <section className="min-h-screen">
          <nav className="p-10 mb-12 flex justify-between dark:text-white">
            <h1 className="text-xl font-burtons uppercase">
              bojan stanimirovski
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-xl"
                />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-cyan-600 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10 ">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Bojan Stanimirovski
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Developer and Designer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-300">
              Freelancer providing services for programming and website design
              needs. Contact me down bellow and let&apos;s get started.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="#">
              <AiFillTwitterCircle />
            </a>
            <a href="#">
              <AiFillLinkedin />
            </a>
            <a href="#">
              <AiFillYoutube />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image classname="object-cover" src={devstan} alt="image" />
          </div>
        </section>
        {/* Second page */}
        <section>
          <div>
            <h4 className="text-3xl py-1 dark:text-white">Services I offer</h4>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              Since the beginning of my journey as a freelance designer and
              developer, I&apos;ve done remote work for
              <span className="text-teal-500"> agencies </span>
              collaborated with talanted people to create
              <span className="text-teal-500"> digital products</span> for both
              business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200 ">
              I offer a range of services, including
              <span className="text-teal-500"> web design</span>,
              <span className="text-teal-500"> development</span> and
              <span className="text-teal-500"> consulting</span>.
            </p>
          </div>

          {/* Card System*/}
          <div className="lg:flex gap-10">
            {/*Design Card*/}
            <div className="text-center shadow-lg p-10 rounded-xl my-10  flex-1 dark:bg-white">
              <Image
                className="mx-auto"
                src={design}
                alt="design-img"
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>

            {/*Development Card*/}
            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-white">
              <Image
                className="mx-auto"
                src={code}
                alt="img"
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">Web Development</h3>
              <p className="py-2">
                Creating elegant websites suited for your needs following core
                programming theory.
              </p>
              <h4 className="py-4 text-teal-600">Programming tools I use</h4>
              <p className="text-gray-800 py-1">MERN Stack</p>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">Tailwind</p>
            </div>

            {/*Consulting Card*/}
            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-white">
              <Image
                className="mx-auto"
                src={consulting}
                alt="img"
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">Consulting</h3>
              <p className="py-2">
                Providing solutions suited for your needs following web
                development theory.
              </p>
              <h4 className="py-4 text-teal-600">Topics that I cover</h4>
              <p className="text-gray-800 py-1">User Expirience</p>
              <p className="text-gray-800 py-1">User Interface</p>
              <p className="text-gray-800 py-1">Design Patherns</p>
            </div>
          </div>
        </section>

        {/* Final Section */}
        <section>
          <h3 className="text-3xl py-1 dark:text-white">Porfolio</h3>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap mx-auto">
            <div className="basis-1/3 flex-1">
              <h3 className="py-4 text-teal-600 font-medium">
                Sneaker Store Design
              </h3>
              <Image
                src={web1}
                alt="web1"
                classname="rounded-lg object-cover w-full h-full "
              />
            </div>

            <div className="basis-1/3 flex-1">
              <h3 className="py-4 text-teal-600 font-medium">
                Elegant Nails Design
              </h3>

              <Image
                src={web2}
                alt="web2"
                classname="rounded-lg object-cover w-full h-full "
              />
            </div>

            <div className="basis-1/3 flex-1">
              <h3 className="py-4 text-teal-600 font-medium">
                Dropnow Project
              </h3>

              <Image
                src={web3}
                alt="web3"
                classname="rounded-lg object-cover w-full h-full"
              />
            </div>

            <div className="basis-1/3 flex-1 ">
              <h3 className="py-4 text-teal-600 font-medium">Gardy Project</h3>

              <Image
                src={web4}
                alt="web4"
                classname="rounded-lg object-cover w-full h-full "
              />
            </div>

            <div className="basis-1/3 flex-1">
              <h3 className="py-4 text-teal-600 font-medium">Aimm Project</h3>

              <Image
                src={web5}
                alt="web5"
                classname="rounded-lg object-cover w-full h-full "
              />
            </div>

            <div className="basis-1/3 flex-1">
              <h3 className="py-4 text-teal-600 font-medium">Nunito Project</h3>

              <Image
                src={web6}
                alt="web6"
                classname="rounded-lg object-cover w-full h-full "
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
